### ISSUE TITLE
Won't compile on MacOS

### ISSUE THREAD

**Issue by Generation2Games** [chunkypixel/atari-dev-studio#22]
Hello, I am trying to compile on MacOS and keep getting ### ERROR: couldn't find bB binaries for Darwin(x86_64). Exiting.

This is my first Mac in years so not quite sure what I am doing to set up on these yet, please can you help me?

**Comment by chunkypixel** [comment]
Hi!
I't looks like there could be in issue with the compilation process due to macOS going 64-bit.  Can you please try unpacking the file below and updating the compiler used by bB in the settings.

[bB-1.5-osx-x86.tar.gz](https://github.com/chunkypixel/atari-dev-studio/files/4314950/bB-1.5-osx-x86.tar.gz)

Updating your settings:
![VirtualBox_MacOS Mojave_11_03_2020_09_10_20](https://user-images.githubusercontent.com/20292815/76363929-308d1880-6378-11ea-8c55-c56579e5f44a.png)

I unpacked the file in downloads and set the path as shown in the pic.  

You will need to give be another 24 hours to update and the extension as I think I'll need to update my virtual macOS install first.  Hope that helps.

**Comment by Generation2Games** [comment]
Thank you for the response, sadly this has not worked as I am now getting NOTE: Building your program using your chosen custom batari Basic compiler.

### ERROR: couldn't find bB binaries for Darwin(x86_64). Exiting.
Cleaning up files generated during compilation...

**Comment by chunkypixel** [comment]
Thanks for the update - you'll need to leave it with me to work out a solution. As said hopefully the next 24 hours.

**Comment by Generation2Games** [comment]
Ok I can wait, you are doing a great job by the way, keep it up!

**Comment by chunkypixel** [comment]
Fixed, refer release 0.3.8.

issue identifying ChMod files for batari Basic and 7800basic where the architecture was hard-coded to x86 (Linux and macOS)

**Comment by Generation2Games** [comment]
Working like a dream now!!! Perfect!!
