### ISSUE TITLE
Does this work on VSCodium?

### ISSUE THREAD

**Issue by Pythone** [chunkypixel/atari-dev-studio#46]
I do not use VS code for telemetry reasons, How do I install on vscodium?

**Comment by chunkypixel** [comment]
Hi @Pythone 

As long as you can install extensions with vscodium (which you should!) then you should be right to go! Search for 'Atari' or 'Atari Dev Studio' to install.

**Comment by Pythone** [comment]
I tried to search, but it is not listed

**Comment by Pythone** [comment]
I tried to install from VSIX and it says that the VS Code version is not compatible, what version do I need?

**Comment by Pythone** [comment]
Unable to install extension 'chunkypixel.atari-dev-studio' as it is not compatible with VS Code '1.52.1'.

**Comment by zephryn** [comment]
I haven't had problems installing the provided VSIX file manually, at least with VSCodium 1.63.2.

@chunkypixel: Non-proprietary Visual Studio Code forks use a different "Marketplace" due to restrictive terms provided by Microsoft for their own extension registry. Might be worth checking out https://open-vsx.org as that's what VSCodium and Code - OSS use by default  to provide extensions AFAIK.

**Comment by chunkypixel** [comment]
Hi guys. Thanks for the information and apologies for not getting to this yet.

When I get a chance I'll take a look and see what can be done.  I've also noted the latest version has done something to the hover messages so will need to get in there soon anyway.

**Comment by chunkypixel** [comment]
Codium extension is now available!
